### ISSUE TITLE
upstream追従コマンドの追加

### ISSUE THREAD

**Issue by ababup1192** [natsumisawa/github-convs#26]
forkしたときに、upstream(fork元)の変更に追従するためのコマンドがほしい。

**Comment by natsumisawa** [comment]
なるほど。次の課題にします。

**Comment by natsumisawa** [comment]
そうか、zpugで追従するのどうやるんだろう、って調べてたけど、
forkしてcloneして使ってもらえば追従するようにできるのか。

**Comment by natsumisawa** [comment]
zplugだったら、zplug updateすればいいだけだった。

**Comment by ababup1192** [comment]
https://qiita.com/xtetsuji/items/555a1ef19ed21ee42873

zplugとかの話とは別！
