### ISSUE TITLE
現在のブランチからPRを開く

### ISSUE THREAD

**Issue by ababup1192** [natsumisawa/github-convs#31]
PRを勝手にブラウザで開くコマンドがあったら最高にノンコアでは！？！？！

**Comment by natsumisawa** [comment]
やったークリア

**Comment by natsumisawa** [comment]
まじ紆余曲折あったけどかなり学びが大きかった

わかったこと
- こういうノンコア削減（＝小さいけど人を助けるもの）機能を作るとなると、詰まっても何時間でも作業できる、だいぶ諦めが悪くなる→その結果効率的かは知らないけど学びが大きい
