### ISSUE TITLE
[優先度高] 内部で実行しているコマンドの詳細が知りたい

### ISSUE THREAD

**Issue by ababup1192** [natsumisawa/github-convs#36]
github-convsで使われているコマンドに慣れてしまうと、内部で何が起こっているのかわからなくなってしまう。もしくは、想定したものと違ったコマンドを叩かれている！と言う事態になりそうなので、どんなコマンドが打たれているかログが出ると嬉しい気がしました！

**Comment by winkichanwi** [comment]
--help ほしい

**Comment by natsumisawa** [comment]
ようやくgit-help作りました👍
