### ISSUE TITLE
[git-psh]PRが無いブランチをpushしたらPRを作る画面を開いて欲しい

### ISSUE THREAD

**Issue by ababup1192** [natsumisawa/github-convs#37]
常にそうとも限らないので、pushしたタイミングで、PR作る画面開く？開かない？みたいなyes/noを聞いてyesならPR作る画面を開いて欲しい。

**Comment by natsumisawa** [comment]
手段は要望とは違いますが、git-opn-pr-crntでPRがなければPR一覧にとばしてすぐ作成ができるようにしました！
