### ISSUE TITLE
[git-open-pr][バグ]

### ISSUE THREAD

**Issue by ababup1192** [natsumisawa/github-convs#38]
GIT_TOKENとGITHUB_TOKENで表記が揺れているせいでバグに

https://github.com/natsumisawa/github-convs/blob/master/.zshrc-github#L92
https://github.com/natsumisawa/github-convs/blob/master/.zshrc-github#L95

**Comment by natsumisawa** [comment]
ほんとだ！echoする文章間違えた・・・ついでにGITHUB_TOKENに直そう。
昨日unsetできない問題を抜け出せず、変数名変えるという苦渋の決断したんですよね・・・

**Comment by ababup1192** [comment]
unsetできない問題わからないかも
