### ISSUE TITLE
[git-che][改善] remoteにpushしていない新規ブランチへcheckoutできる

### ISSUE THREAD

**Issue by winkichanwi** [natsumisawa/github-convs#42]
## AS-IS
もうoriginにpushしたremote branch存在するブランチだけ
git-cheでcheckoutできる

## TO-BE
まだremote branch存在していないlocal branchも
fzf promotしたブランチメニューでも見えて、選択でき、checkoutできる

**Comment by natsumisawa** [comment]
issueくれて嬉しい。笑
一度でもlocalでcheckoutしたことあるブランチだったらgit-cheでいけるはずだが・・・

**Comment by winkichanwi** [comment]
git-cheのブランチリストにはそのlocal branchはいなかった :cry:

**Comment by natsumisawa** [comment]
再現しなかった・・・🙇
でも別のバグ見つけた。
checkoutした後にpullしているんだけど、pullはoriginがないから `fatal: Couldn't find remote ref #42_fix_git_che` ってなっていた。

**Comment by winkichanwi** [comment]
それです！そのエラーでたらcheckoutできなかったと思っていた

**Comment by natsumisawa** [comment]
リモートになかったらpullしないようにしました〜！
