### ISSUE TITLE
[ノンコア] git-cheする時に元いたブランチは必ずgit-pshしていいと思うんだけどどう思う？

### ISSUE THREAD

**Issue by natsumisawa** [natsumisawa/github-convs#44]
git-pshし忘れて家で作業できなかったり、元にいたブランチにもどらなきゃいけなくなったりしない
でも毎回pshしたいわけでもないと思うから、
commitしたら「pshする？」って出したらどうだろう

**Comment by natsumisawa** [comment]
というかコミットしたら聞く、でもいいか。

**Comment by ababup1192** [comment]
基本pushしたい。
大体の場合テスト書いているし、CI回せる状態になっている RED上等
