### ISSUE TITLE
git-add-cmtのコミットメッセージの挙動

### ISSUE THREAD

**Issue by ababup1192** [natsumisawa/github-convs#60]
コミットメッセージをおそらくreadコマンドを使ってやっていると思われますが、日本語をコミットメッセージに含める際におかしな挙動になります。

なので、通常のgitと同じように -m でコマンドと共に渡す。そうじゃないときはエディタが開くとという仕様にするのはどうでしょう？

**Comment by ababup1192** [comment]
git commit -m "初めてコミットしてみた"

もしくは、vim等のエディタが開いてメッセージが編集できるってことです。

**Comment by natsumisawa** [comment]
> git commit -m "初めてコミットしてみた"

今って👆こうなってますよね・・・？

EDITOR！！ありがとうございます👍

**Comment by ababup1192** [comment]
それは内部的な話〜

git-add-cmt -m hogehoge

こう書いた方が良いかな？
